name: Build and Release VSIX

on:
  push:
    branches:
      - master  # Run this workflow on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can use other runners if needed

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the version of Node.js you need

      # Install vsce (Visual Studio Code Extension Manager)
      - name: Install vsce
        run: npm install -g vsce

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Package the extension to .vsix
      - name: Package VSIX
        run: vsce package

      # Create a release and upload the .vsix file
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub provides this secret automatically
        with:
          tag_name: v${{ github.sha }}  # Use the commit hash as the version tag, or replace with a custom version
          release_name: "VSIX Release v${{ github.sha }}"
          draft: false  # Set to true if you want the release to be in draft mode
          prerelease: false

      # Upload the VSIX file to the release
      - name: Upload VSIX to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./*.vsix  # Ensure the correct path to the .vsix file
          asset_name: my-extension.vsix  # Name of the .vsix file
          asset_content_type: application/octet-stream
